[first]
# Min width of peak to consider.
thr_min_peak_width = 20

# Min width of valley to consider.
thr_min_valley_width = 20

# Valleys with a coverage depth at least this percent of the mean coverage are considered misjoins.
# ex. 0.9
# Valleys that dip 90% of the mean coverage are misjoins.
thr_misjoin_valley = 0.95

# Valleys with a majority of the positions below a depth at least this percent of the mean coverage are considered false-duplications.
# Must also intersect with a misjoin.
thr_false_dupe_valley = 0.4

# Peaks with a coverage height at least this percent of the mean coverage are considered collapses.
# ex. 2.25
# Peaks with a height of 225% of the mean coverage are considered collapses
thr_collapse_peak = 2.25

# Group consecutive positions allowing a maximum gap of x.
# Larger value groups more positions.
valley_group_distance = 5000

peak_group_distance = 5000

# For false dupes which can have noisy signal dip.
# Allows only grouping regions by x bp that are potential false dupes.
# Won't group over non-false-dupe regions between false-dupe regions that have a relative height of thr_false_dupe_valley + false_dupe_group_stdev stdevs
false_dupe_group_distance = 250000

false_dupe_group_stdev = 1.5

# Fit second order polynomial to peaks/valleys to reduce effect of outliers.
fit_second_order_poly = false

[second]
# Percent threshold of most freq base to allow second most freq base
# ex. 0.1 and a mean coverage of 30.
# 30 * 0.1 = 3 so above 3 is allowed.
thr_min_perc_first = 0.05

# Group consecutive positions allowing a maximum gap of x.
# Larger value groups more positions.
group_distance = 10_000

# Min group size.
thr_min_group_size = 5

# Regions with a het ratio below this are hets. Otherwise, considered an error.
# Lower values will call more het sites as errors.
thr_het_ratio = 0.2

[general]
# Window size. Only applicable if no region bed file is provided.
window_size = 10_000_000
