import os

SAMPLES = [
    "HG00514",
    "HG00864",
    "NA12329",
    "NA19240",
    "NA19238",
    "HG00732",
    "NA18939",
    "HG00512",
    "HG03732",
    "HG00096",
    "NA19239",
    "HG00513",
]


wildcard_constraints:
    sm='|'.join(SAMPLES)


rule nucplot:
    input:
        bam="data/{sm}_hifi.bam",
        bed="data/{sm}_ALR_regions.500kbp.bed",
        config="config/config.toml",
        ignore_bed="config/ignore_regions.bed",
    output:
        plot_dir=directory(os.path.join("output", "{sm}")),
        misassemblies=os.path.join("output", "{sm}_misassemblies.bed")
    threads:
        12
    conda:
        "env.yaml"
    log:
        "logs/{sm}.log"
    benchmark:
        "benchmarks/{sm}.tsv"
    shell:
        """
        nucfreq \
        -i {input.bam} \
        -b {input.bed} \
        -d {output.plot_dir} \
        -o {output.misassemblies} \
        -p {threads} \
        -t {threads} \
        -c {input.config} \
        --ignore_regions {input.ignore_bed} 2> {log}
        """


rule all:
    input:
        expand(rules.nucplot.output, sm=SAMPLES)
    default_target:
        True
