name: Publish
on:
  release:
    types: [published]

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  directory.
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python.
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies.
        run: |
          make venv && make build

      - name: Publish package.
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_NUCFLAG_TOKEN }}
